import type { SynthVService } from "./synthv-service.js";
export type SynthVCommandHandler = (params: Record<string, unknown>) => Promise<unknown>;
export interface SynthVCommandRegistry { register(command: string, handler: SynthVCommandHandler): void; }

export function registerSynthVCommands(registry: SynthVCommandRegistry, service: SynthVService): void {
  const add = (name: string, handler: SynthVCommandHandler) => registry.register(name, handler);
  add("scan_synthv", () => service.scanInstallations()); add("sv2_profile_state", () => service.profileState()); add("sv2_cached_profile_state", () => service.profileState()); add("sv2_voice_catalog", () => service.voiceCatalog());
  add("sv2_account_precheck", p => service.accountPrecheck(optional(p, "slotId"))); add("sv2_account_usage_snapshot", async () => ({ profiles: await service.profileState(), precheck: await service.accountPrecheck() })); add("sv2_account_usage_snapshot_for_slot", async p => ({ profiles: await service.profileState(), precheck: await service.accountPrecheck(text(p, "slotId")) }));
  add("create_sv2_profile", p => service.createProfile(text(p, "displayName"))); add("import_current_sv2_profile", p => service.createProfile(text(p, "displayName"))); add("rename_sv2_profile", p => service.renameProfile(text(p, "slotId"), text(p, "displayName"))); add("delete_sv2_profile", p => service.deleteProfile(text(p, "slotId"))); add("activate_sv2_profile", p => service.activateProfile(text(p, "slotId"))); add("prepare_sv2_concurrent_profile", p => service.prepareConcurrentProfile(text(p, "slotId"))); add("open_sv2_profile_folder", p => service.openProfileFolder(text(p, "slotId")));
  add("launch_sv2_profile", p => service.launchProfile(text(p, "slotId"), optional(p, "projectPath"))); add("force_launch_sv2_profile", p => service.launchProfile(text(p, "slotId"), optional(p, "projectPath"))); add("launch_sv2_concurrent_profile", p => service.launchConcurrentProfile(text(p, "slotId"), optional(p, "projectPath")));
  add("read_sv2_session_document", async p => session(await service.readSession(text(p, "slotId")))); add("write_sv2_session_document", async p => session(await service.writeSession(text(p, "slotId"), text(p, "plaintext"), text(p, "expectedSha256")))); add("sv2_inspect_offline_license", p => service.inspectOfflineLicense(text(p, "slotId"))); add("sv2_set_offline_license", p => service.setOfflineLicense(text(p, "slotId"), bool(p, "enabled"))); add("preview_sv2_offline_session_replacement", p => service.previewOfflineSessionReplacement(text(p, "slotId"), text(p, "sourcePath"))); add("schedule_sv2_offline_session_replacement", p => service.scheduleOfflineSessionReplacement(text(p, "slotId"), text(p, "sourcePath"), text(p, "sourceSha256"), text(p, "destinationSha256")));
  add("sv2_sync_categories", async () => [{ id: "settings", title: "Settings", description: "Application settings", defaultSelected: true }, { id: "database", title: "Database", description: "Local databases", defaultSelected: true }, { id: "voice", title: "Voice", description: "Voice data", defaultSelected: false }]); add("preview_sv2_selective_sync", p => service.previewSelectiveSync(text(p, "sourceSlotId"), text(p, "targetSlotId"), strings(p, "categories"), bool(p, "overwrite"))); add("execute_sv2_selective_sync", p => service.executeSelectiveSync(text(p, "sourceSlotId"), text(p, "targetSlotId"), strings(p, "categories"), token(p)));
  add("update_sv2_concurrent_defaults", p => service.concurrentDefaults(bool(p, "appSettings"), bool(p, "voiceLibraries"))); add("update_sv2_concurrent_content", p => service.concurrentContent(text(p, "slotId"), text(p, "appSettings"), text(p, "voiceLibraries")));
  add("preview_svp_route", p => service.previewSvpRoute(text(p, "projectPath"))); add("launch_svp_route", p => service.launchSvpRoute(text(p, "slotId"), text(p, "projectPath"), text(p, "mode"))); add("pending_svp_route", () => Promise.resolve(service.pendingSvpRoute())); add("open_svp_default_apps_settings", () => service.openDefaultAppsSettings());
  add("list_synthv_processes", () => service.listProcesses()); add("focus_sv2_instance", p => service.focusInstance(int(p, "processId"), text(p, "processIdentity"))); add("terminate_sv2_instance", p => service.terminateInstance(int(p, "processId"), text(p, "processIdentity"))); add("synthv_shortcut_profile", () => Promise.resolve(service.shortcutProfile())); add("send_synthv_bridge_shortcut", p => service.sendShortcut(int(p, "processId"), text(p, "processIdentity"), shortcut(p)));
  add("install_bridge", p => service.installBridge(targets(p))); add("diagnose_bridge", p => service.diagnoseBridge(targets(p))); add("connect_bridge", () => service.connectBridge()); add("bridge_session_status", () => service.bridgeStatus()); add("auto_connect_synthv_bridge", () => service.connectBridge()); add("stop_synthv_bridge", () => service.stopBridge()); add("set_autostart", p => service.setAutostart(bool(p, "enabled"))); add("get_autostart", () => service.getAutostart());
}
function text(p: Record<string, unknown>, k: string): string { const v = p[k]; if (typeof v !== "string" || !v.trim()) throw new Error(`${k} must be a non-empty string.`); return v; } function optional(p: Record<string, unknown>, k: string): string | undefined { return p[k] == null ? undefined : text(p, k); } function bool(p: Record<string, unknown>, k: string): boolean { if (typeof p[k] !== "boolean") throw new Error(`${k} must be a boolean.`); return p[k] as boolean; } function int(p: Record<string, unknown>, k: string): number { const v = p[k]; if (typeof v !== "number" || !Number.isSafeInteger(v) || v <= 0) throw new Error(`${k} must be a positive integer.`); return v; } function strings(p: Record<string, unknown>, k: string): string[] { const v = p[k]; if (!Array.isArray(v) || !v.every(x => typeof x === "string")) throw new Error(`${k} must be a string array.`); return v; } function shortcut(p: Record<string, unknown>): string { const v = text(p, "action"); if (v !== "start" && v !== "stop") throw new Error("action must be start or stop."); return v; } function targets(p: Record<string, unknown>): Array<{ scriptsPath: string; bridgeProfile: string }> { const v = p.targets; if (!Array.isArray(v)) throw new Error("targets must be an array."); return v.map(x => { if (x === null || typeof x !== "object" || Array.isArray(x)) throw new Error("Bridge target must be an object."); return { scriptsPath: text(x as Record<string, unknown>, "scriptsPath"), bridgeProfile: text(x as Record<string, unknown>, "bridgeProfile") }; }); } function token(p: Record<string, unknown>): string { const a = p.approved; if (a === null || typeof a !== "object" || Array.isArray(a)) throw new Error("approved must be a sync preview."); return text(a as Record<string, unknown>, "token"); } function session(v: { path: string; sha256: string; plaintext?: string }): Record<string, unknown> { return { path: v.path, encryptedSha256: v.sha256, encryptedBytes: v.plaintext?.length ?? 0, plaintext: v.plaintext ?? "", backupPath: null }; }
