import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const read = (path) => readFileSync(join(root, path), "utf8");
const main = read("src/PiDesktop.Tauri/src/main.ts");
const api = read("src/PiDesktop.Tauri/src/api.ts");
const types = read("src/PiDesktop.Tauri/src/types.ts");
const i18n = read("src/PiDesktop.Tauri/src/i18nAi.ts");
const commands = read("src/PiDesktop.Tauri/src-tauri/src/commands.rs");
const lib = read("src/PiDesktop.Tauri/src-tauri/src/lib.rs");
const settings = main.slice(main.indexOf("function renderSettings"), main.indexOf("async function refreshAutostartStatus"));

assert.match(main, /type Page = .*"ai"/);
assert.match(main, /navItem\("ai", t\("nav\.ai"\)/);
assert.match(main, /case "ai": return renderAiPage\(\)/);
assert.match(main, /shellController\.afterUpdate\(\(\) => \{/);
assert.match(main, /syncModelConnectionPanel\(\);/);
assert.match(main, /toolboxEventsBound/);
assert.match(main, /<model-connection-panel><\/model-connection-panel>/);
assert.match(main, /data-refresh-ai-usage/);
assert.match(main, /ai-usage-table/);
assert.match(main, /formatPercentage\(value\)/);
assert.match(main, /import \{ formatPercentage \} from "\.\/percentage"/);
assert.match(main, /usageEnabled: provider\.id === "anthropic" \|\| provider\.id === "openai-codex"/);
assert.match(main, /usage: usageByCredential\.get\(account\.id\) \?\? null/);
assert.match(main, /case "query-usage"/);
assert.doesNotMatch(settings, /model-connection-panel|renderAiProviderSettings/);
assert.match(api, /aiProviderUsage: \(\) => call<AiProviderUsageSnapshot>\("ai_provider_usage"\)/);
assert.match(api, /command === "ai_provider_usage"/);
assert.match(types, /interface AiProviderUsageSnapshot/);
assert.match(types, /channel: "oauth" \| "preview"/);
assert.match(types, /interface AiProviderUsage/);
assert.match(commands, /pub async fn ai_provider_usage/);
assert.match(lib, /commands::ai_provider_usage/);
assert.match(i18n, /addMessages\("zh-CN"/);
assert.match(i18n, /addMessages\("en"/);

console.log("AI page navigation, connection projection, usage table, refresh entry, and bilingual contracts passed.");
