import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { createRequire, stripTypeScriptTypes } from 'node:module';
const require = createRequire(new URL('../src/PiDesktop.Tauri/package.json', import.meta.url));
const { parse } = require('@babel/parser');
const read = path => fs.readFileSync(new URL('../' + path, import.meta.url), 'utf8');
const main = read('src/PiDesktop.Tauri/src/main.ts');
const body = parse(main, { sourceType: 'module', plugins: ['typescript'] }).program.body;
const functionSource = name => { const fn = body.find(n => n.type === 'FunctionDeclaration' && n.id.name === name); assert.ok(fn, name); return stripTypeScriptTypes(main.slice(fn.start, fn.end), { mode: 'transform' }); };
const context = vm.createContext({ t: key => key });
vm.runInContext(functionSource('featureAvailability'), context);
context.feature = { id: 'audio-preparation', componentIds: ['ffmpeg'] };
context.current = { platform: 'windows', components: [{ id: 'ffmpeg', installed: false, installable: true }] };
assert.notEqual(vm.runInContext('featureAvailability(feature, current).route', context), 'components');
context.current.components[0].installable = false;
assert.equal(vm.runInContext('featureAvailability(feature, current).route', context), 'components');
context.current.components[0].installable = true;
context.feature.componentIds.push('pi-audio');
assert.equal(vm.runInContext('featureAvailability(feature, current).route', context), 'components');
let scheduled;
const pollContext = vm.createContext({ app: { downloads: [] }, busy: true, audioProbeInFlight: false, audioPlanRequestInFlight: false, audioLoudnessAnalysisInFlight: false, audioJob: undefined, mediaTasks: [], page: 'import', downloadPollTimer: undefined, window: { setTimeout(callback) { scheduled = callback; return 1; } }, api: { componentDownloads: async () => [{ componentId: 'ffmpeg', status: 'downloading', progress: 30 }] }, render() {}, refresh: async () => {}, refreshAudioPreparationIfSelected() {} });
vm.runInContext(functionSource('scheduleDownloadPoll') + '\nscheduleDownloadPoll()', pollContext);
assert.equal(typeof scheduled, 'function', 'First demand must discover a queue that was initially empty');
await scheduled();
assert.equal(pollContext.app.downloads[0].progress, 30);
assert.doesNotMatch(main, /!audioPrepareForm.inputPath \|\| !runtime\?\.available/);
assert.match(main, /!audioPrepareForm.inputPath \|\| !runtimeUsable/);
const rust = name => read('src/PiDesktop.Tauri/src-tauri/src/' + name + '.rs');
const queue = rust('downloads');
assert.match(queue, /manager\.enqueue\("ffmpeg"\)/);
assert.match(queue, /manager\.wait_for_installation\(&task_id, cancelled\)/);
assert.match(queue, /cfg!\(all\(windows, target_arch = "x86_64"\)\)/);
assert.match(queue, /ffmpeg_runtime_available\(resource_dir\)[\s\S]*return Ok\(\(\)\);/);
assert.match(rust('state'), /downloads::shared_downloads\(\)/);
const audio = rust('audio_prep');
assert.match(audio, /self\.ensure_runtime\(None\)\.await\?;\s*let _usage_guard/);
assert.match(audio, /self\.ensure_runtime\(Some\(Arc::clone\(&cancelled\)\)\)\.await\?;\s*let _usage_guard/);
assert.doesNotMatch(audio.slice(audio.indexOf('pub async fn status'), audio.indexOf('pub async fn probe_media')), /ensure_runtime|ensure_ffmpeg/);
assert.match(rust('workflows'), /ensure_ffmpeg_blocking\(resource_dir, None\)\?;\s*let runtime = python_component/);
assert.match(rust('media_import'), /if !rights_confirmed[\s\S]*ensure_ffmpeg\(resource_root.clone\(\), Some\(Arc::clone\(&cancelled\)\)\)/);
assert.match(functionSource('startPlannedAudioJob'), /pendingAudioPlan/);
console.log('Automatic FFmpeg UI demand discovery, supported-platform gating, and backend integration contracts passed.');
