export const englishFeatureMessages = {
  cover: { title: "One-click Cover", description: "Download a BV or YouTube source, separate vocals, extract a melody, map lyrics, and import into the current SynthV project.", base: ["Source to two tracks", "Melody MIDI and lyrics", "Automatic F13 Bridge connection"], ai: ["Quick workflow commands", "Voice authorization guidance", "Explain failures and retry"], requirements: ["Media importer", "Vocal separation", "pi-audio", "SynthV Bridge"] },
  "tuning-learning": { title: "Voice-specific tuning", description: "Extract performance features from reference vocals and learn bounded tuning parameters separately for each voice.", base: ["Offline vocal features", "Per-voice profiles", "A/B feedback updates"], ai: ["Parameter suggestions", "Safe Bridge application", "Solo iteration support"], requirements: ["pi-audio", "SynthV Bridge (when applying)"] },
  "media-import": { title: "BV / YouTube audio import", description: "Preview a Bilibili or YouTube source and download a managed WAV after confirming your rights to use it.", base: ["BV / URL metadata preview", "Managed WAV and SHA-256", "Source and rights records"], ai: ["Separation and Cover workflows", "Source details", "Failure classification"], requirements: ["media-fetcher", "FFmpeg", "Node.js 22+"] },
  "source-separation": { title: "Vocal / instrumental separation", description: "Separate a mixed source into vocal and instrumental WAV files using managed Demucs htdemucs.", base: ["Two-track Demucs separation", "Stable vocals / inst outputs", "Managed local directory"], ai: ["Cover workflow integration", "Separation result review", "Model failure explanations"], requirements: ["Vocal separation component", "FFmpeg"] },
  "score-to-synthv": { title: "Import a score into SynthV", description: "Convert a local MIDI or MusicXML score into a monophonic note group in the current SynthV project.", base: ["MIDI / MusicXML input", "Monophonic note conversion", "File fingerprint checks"], ai: ["Part selection guidance", "Import review", "Tuning planning"], requirements: ["SynthV Bridge"] },
  "audio-to-project": { title: "Vocals → MIDI / SynthV", description: "Extract a monophonic melody from aligned vocal and instrumental versions, then export MIDI or import into SynthV.", base: ["Paired audio difference", "Standard MIDI export", "Optional Bridge import"], ai: ["Candidate parameter search", "Low-confidence note correction", "Import review"], requirements: ["FFmpeg", "pi-audio", "Bridge (optional)"] },
  "audio-preparation": { title: "Audio preparation", description: "Prepare local audio as editable PCM WAV for SynthV, and check or normalize loudness using EBU R128 when needed.", base: ["Media inspection", "PCM WAV conversion", "Loudness analysis and normalization"], ai: ["Parameter suggestions", "Result review", "Delivery risk guidance"], requirements: ["FFmpeg"] },
  "audio-insight": { title: "Audio structure analysis", description: "Extract tempo, beats, key, energy, and spectral trends to inform arrangement, tuning, and review.", base: ["BPM / beats / key", "Energy and spectrum curves", "Structured analysis report"], ai: ["Section and style summaries", "Explain unusual passages", "Production suggestions"], requirements: ["FFmpeg", "pi-audio"] },
  "project-tools": { title: "SV project files", description: "Inspect saved .svp files, create reference tracks or parameter-free copies, and export line or word-timed LRC.", base: ["Project structure inspection", "Safe project copies", "Line / word-timed LRC"], ai: ["Project risk explanations", "Draft change plans", "Batch result review"], requirements: ["CVRS"] },
  "ab-audition": { title: "A/B clip review", description: "Capture short SynthV playback clips and compare changes after aligning loopback latency, without rendering the whole project again.", base: ["Process audio capture", "Playhead restoration and interruption checks", "Fast A/B alignment"], ai: ["Review local edits", "Explain difference metrics", "Compare successive candidates"], requirements: ["Windows 10 20348+", "SynthV Bridge"] },
  "retake-compare": { title: "Retake workbench", description: "Inspect a note's Retake candidates, generate pitch, timing, or timbre variations, and switch or remove candidates after freshness checks.", base: ["Read candidates", "Three-dimensional Retake generation", "Safe switching and removal"], ai: ["Candidate difference summaries", "Listening target suggestions", "Explain retained candidates"], requirements: ["SynthV Bridge"] },
  "project-doctor": { title: "Project diagnostics", description: "Scan project versions, notes, lyrics, references, and parameter curves offline to produce a report with specific issue locations.", base: ["Structural integrity checks", "Note and reference diagnostics", "Deterministic risk levels"], ai: ["Explain issue impact", "Prioritize fixes", "Conservative change plans"], requirements: ["Local .svp file"] },
  "pronunciation-doctor": { title: "Pronunciation diagnostics", description: "Check a project or pasted lyrics for empty syllables, crowded syllables, mixed scripts, and very short notes.", base: ["Lyric structure checks", "Short-note pronunciation risks", "Specific issue locations"], ai: ["Explain pronunciation issues", "Phoneme suggestions", "Cross-language review"], requirements: ["Local .svp file or lyrics"] },
  "render-review": { title: "Render review", description: "Check clipping, silence, and loudness jumps, then review delivery risks against expected duration, BPM, and pitch events.", base: ["Clipping and silence detection", "Loudness continuity checks", "Delivery checklist"], ai: ["Explain suspicious passages", "Risk level explanations", "Review summaries"], requirements: ["FFmpeg", "pi-audio"] },
  "batch-recipes": { title: "Batch processing", description: "Apply project, pronunciation, and render checks, structure inspection, or parameter-free export to a group of files.", base: ["Built-in safe recipes", "Up to 100 sequential items", "Individual failure isolation"], ai: ["Failure classification", "Batch result summaries", "Parameter suggestions"], requirements: ["Required local components"] },
  "selective-sync": { title: "Account resource sync", description: "Selectively sync dictionaries, scripts, presets, and safe settings between account slots, excluding login state and voice databases.", base: ["Allowed categories", "SHA-256 difference preview", "Conflict and stale-manifest protection"], ai: ["Explain conflicts", "Suggest sync scope", "Post-sync review"], requirements: ["Windows", "At least two slots"] },
};

export const englishGroupMessages = {
  import: { title: "Import & Convert", description: "Turn scores and vocal audio into editable MIDI and SynthV notes." },
  quality: { title: "Analysis & QA", description: "Run audio analysis, project diagnostics, pronunciation checks, and delivery review." },
};
