import { addMessages } from "./i18n";

addMessages("zh-CN", { header: { processing: "处理中", allSettings: "全部设置", addAccount: "添加账号" } });
addMessages("en", { header: { processing: "Working", allSettings: "All settings", addAccount: "Add account" } });
addMessages("zh-CN", { accounts: { profile: "账号设置", manager: "账号管理", managerNote: "备注", availableAuthorizations: "可用授权", unread: "未读取", data: "账号数据", macScope: "macOS 槽位范围", importDescription: "把现有官方数据目录纳入槽位，不移动账号文件。", emptyDescription: "首次启动后，在 SV2 官方登录页面完成登录。", safety: "账号数据保持原样", safetyDescription: "工具箱不会伪造登录或绕过联网验证。" } });
addMessages("en", { accounts: { profile: "Account settings", manager: "Account manager", managerNote: "Note", availableAuthorizations: "Available authorizations", unread: "Not read", data: "Account data", macScope: "macOS slot scope", importDescription: "Bring the existing official data directory into a slot without moving account files.", emptyDescription: "Complete sign-in on the official SV2 page after first launch.", safety: "Account data stays unchanged", safetyDescription: "Toolbox does not fabricate sign-in or bypass online verification." } });

addMessages("zh-CN", { accounts: { unsupported: "当前平台不支持账号槽位", blocked: "普通槽位暂时不能切换", recovery: "槽位需要人工恢复", recheck: "重新检查", officialPath: "官方路径", vault: "保管区", neverLaunched: "尚未启动", pending: "账号信息待刷新", signedOut: "未登录", note: "备注：{name}", noNote: "未设置备注", default: "默认", addFirst: "添加第一个账号", addFirstDescription: "导入当前环境或创建空槽位", settings: "账号设置", manager: "账号管理", close: "关闭", saveNote: "保存备注", setDefault: "设为默认账号", openData: "打开账号数据目录", delete: "删除账号", noAccounts: "尚无账号，请先添加一个槽位。", global: "全局设置", saveGlobal: "保存全局设置", enableIndicator: "启用账号登录指示器", enableIsolation: "启用隔离功能", importCurrent: "导入当前环境", createEmpty: "创建空槽位", import: "导入", create: "创建", notePlaceholder: "备注（可留空）", consentTitle: "开启账号登录指示器？", consentConfirm: "同意并开启", cancel: "取消", deleteTitle: "删除“{name}”？", deleteConfirm: "删除账号", switchDefault: "切换默认账户", refresh: "刷新此账号状态", configure: "设置", concurrentTitle: "并发隔离未被官方承认", concurrentContinue: "已知晓风险，继续启动", consentDescription: "开启后可在账号页面或手动刷新时查询账号授权状态。", deleteDescription: "这会删除该账号的数据、隔离环境配置和登录态恢复快照，无法撤销。" } });
addMessages("en", { accounts: { unsupported: "Account slots are unavailable on this platform", blocked: "Standard slots cannot be switched right now", recovery: "This slot needs manual recovery", recheck: "Check again", officialPath: "Official path", vault: "Vault", neverLaunched: "Not launched yet", pending: "Account information needs refresh", signedOut: "Signed out", note: "Note: {name}", noNote: "No note", default: "Default", addFirst: "Add your first account", addFirstDescription: "Import the current environment or create an empty slot", settings: "Account settings", manager: "Account manager", close: "Close", saveNote: "Save note", setDefault: "Make default", openData: "Open account data folder", delete: "Delete account", noAccounts: "No accounts yet. Add a slot first.", global: "Global settings", saveGlobal: "Save global settings", enableIndicator: "Enable account sign-in indicator", enableIsolation: "Enable isolation", importCurrent: "Import current environment", createEmpty: "Create empty slot", import: "Import", create: "Create", notePlaceholder: "Note (optional)", consentTitle: "Enable the account sign-in indicator?", consentConfirm: "Accept and enable", cancel: "Cancel", deleteTitle: "Delete {name}?", deleteConfirm: "Delete account", switchDefault: "Switch default account", refresh: "Refresh account status", configure: "Settings", concurrentTitle: "Concurrent isolation is not officially supported", concurrentContinue: "I understand the risk and want to continue", consentDescription: "When enabled, account authorization can be checked from the accounts page or manually.", deleteDescription: "This permanently removes the account data, isolated-environment configuration, and sign-in recovery snapshot." } });
