import { addMessages } from "./i18n";

addMessages("zh-CN", { about: {
  nav: "关于", product: "产品信息", productDescription: "Synthesizer V 创作工具与本机工作流中心。", build: "构建版本", platform: "平台", license: "许可证", project: "项目主页", guidance: "使用指南", issues: "报告问题",
  updates: "应用更新", updatesDescription: "选择渠道、检查发布并在此下载更新。", channel: "更新渠道", stable: "稳定版", nightly: "Nightly", stableDescription: "只接收正式发布版本。", nightlyDescription: "接收最新开发构建，可能不稳定。", currentVersion: "当前版本", check: "检查更新", checkAgain: "重新检查", available: "有可用更新", current: "已是最新版本", newer: "当前版本较新", published: "发布于", checked: "检查于", releaseNotes: "发行说明", noNotes: "此版本未提供发行说明。", latestStable: "最新稳定版", latestNightly: "最新 Nightly 版本",
  download: "下载更新", downloading: "正在下载更新", downloaded: "已下载 {current} / {total}", downloadedUnknown: "已下载 {current}", cancelDownload: "取消下载", discardDownload: "丢弃下载", retryDownload: "重新下载", readyToInstall: "更新已准备就绪", installWindows: "安装更新", openDiskImage: "打开磁盘映像", macInstallGuide: "打开磁盘映像后，请将 Synthesizer V Toolbox 拖到 Applications 文件夹完成安装。", downloadFailed: "下载失败", noInstaller: "此发布没有适用于当前平台的安装包。", openRelease: "打开发布页"
} });

addMessages("en", { about: {
  nav: "About", product: "Product information", productDescription: "Synthesizer V creation tools and local workflow hub.", build: "Build", platform: "Platform", license: "License", project: "Project home", guidance: "Guides", issues: "Report an issue",
  updates: "App updates", updatesDescription: "Choose a channel, check releases, and download updates here.", channel: "Update channel", stable: "Stable", nightly: "Nightly", stableDescription: "Receive released versions only.", nightlyDescription: "Receive the newest development build; it may be unstable.", currentVersion: "Current version", check: "Check for updates", checkAgain: "Check again", available: "Update available", current: "Up to date", newer: "Current version is newer", published: "Published", checked: "Checked", releaseNotes: "Release notes", noNotes: "No release notes were provided for this version.", latestStable: "Latest stable version", latestNightly: "Latest nightly version",
  download: "Download update", downloading: "Downloading update", downloaded: "Downloaded {current} / {total}", downloadedUnknown: "Downloaded {current}", cancelDownload: "Cancel download", discardDownload: "Discard download", retryDownload: "Retry download", readyToInstall: "Update ready", installWindows: "Install update", openDiskImage: "Open disk image", macInstallGuide: "After opening the disk image, drag Synthesizer V Toolbox to the Applications folder to install it.", downloadFailed: "Download failed", noInstaller: "This release has no installer for the current platform.", openRelease: "Open release page"
} });
