import {
  ArrowRight,
  AudioWaveform,
  Bot,
  Boxes,
  BriefcaseBusiness,
  Cable,
  Check,
  ClipboardList,
  createElement,
  Download,
  FilePenLine,
  FileInput,
  FileText,
  Folder,
  GitCompareArrows,
  History,
  House,
  Info,
  ListChecks,
  Music,
  Play,
  PlugZap,
  Plus,
  RefreshCw,
  Send,
  Server,
  Settings,
  ShieldCheck,
  Sparkles,
  Speech,
  Stethoscope,
  Trash2,
  TriangleAlert,
  Users,
  Workflow,
  type IconNode,
} from "lucide";

const icons = {
  home: House,
  users: Users,
  toolbox: BriefcaseBusiness,
  bot: Bot,
  boxes: Boxes,
  plug: PlugZap,
  bridge: Cable,
  settings: Settings,
  sparkles: Sparkles,
  audio: Music,
  file: FileText,
  import: FileInput,
  download: Download,
  plus: Plus,
  play: Play,
  folder: Folder,
  send: Send,
  check: Check,
  refresh: RefreshCw,
  arrow: ArrowRight,
  server: Server,
  trash: Trash2,
  pipeline: Workflow,
  doctor: Stethoscope,
  history: History,
  info: Info,
  github: ArrowRight,
  warning: TriangleAlert,
  batch: ListChecks,
  sync: RefreshCw,
  compare: GitCompareArrows,
  pronunciation: Speech,
  lyrics: FilePenLine,
  waveform: AudioWaveform,
  recipe: ClipboardList,
  shield: ShieldCheck,
} satisfies Record<string, IconNode>;

export type IconName = keyof typeof icons;

export function icon(name: IconName, size = 20): string {
  return createElement(icons[name], {
    "aria-hidden": "true",
    class: "icon",
    height: size,
    width: size,
  }).outerHTML;
}
